import type { ResolvedFactoryManifest, SupabaseService } from "./types.ts";

export interface DockerProjectAllocation {
  hostId: string;
  apiGatewayPort: number;
  composeProjectName?: string;
}

export interface DockerRuntimeLayout {
  composeProjectName: string;
  apiGatewayPort: number;
  realtimeTenantName: string;
  realtimeDnsName: string;
  activeComposeServices: readonly string[];
  disabledComposeServices: readonly string[];
}

const BASE_COMPOSE_SERVICES = [
  "studio",
  "api-gw",
  "auth",
  "rest",
  "realtime",
  "storage",
  "imgproxy",
  "meta",
  "functions",
  "db",
  "supavisor",
] as const;

const LOGICAL_TO_COMPOSE: Readonly<Record<SupabaseService, readonly string[]>> = {
  database: ["db", "supavisor"],
  auth: ["auth"],
  rest: ["rest"],
  gateway: ["api-gw"],
  storage: ["storage", "imgproxy"],
  realtime: ["realtime"],
  functions: ["functions"],
  studio: ["studio", "meta"],
  analytics: [],
};

function slug(value: string, max = 63): string {
  const normalized = value
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-+/g, "-");
  return normalized.slice(0, max).replace(/-+$/g, "");
}

export function resolveDockerRuntimeLayout(
  manifest: ResolvedFactoryManifest,
  allocation: DockerProjectAllocation,
): DockerRuntimeLayout {
  if (!Number.isInteger(allocation.apiGatewayPort) || allocation.apiGatewayPort < 1024 || allocation.apiGatewayPort > 65535) {
    throw new Error("apiGatewayPort must be an integer between 1024 and 65535");
  }

  const active = new Set<string>();
  for (const logicalService of manifest.services) {
    for (const composeService of LOGICAL_TO_COMPOSE[logicalService]) active.add(composeService);
  }

  // The database stack is an implementation requirement for the current official
  // self-hosted Docker distribution even when omitted accidentally in a future profile.
  active.add("db");
  active.add("supavisor");
  active.add("api-gw");

  const composeProjectName = slug(allocation.composeProjectName ?? `sbf-${manifest.project.id}`);
  if (composeProjectName.length < 3) throw new Error("compose project name resolved to an invalid value");

  // Realtime identifies its self-hosted tenant from the request host. Keep the
  // official `<tenant>.supabase-realtime` convention but scope the tenant per project.
  const realtimeTenantName = slug(`sbf-${manifest.project.id}`, 48);
  const realtimeDnsName = `${realtimeTenantName}.supabase-realtime`;

  return {
    composeProjectName,
    apiGatewayPort: allocation.apiGatewayPort,
    realtimeTenantName,
    realtimeDnsName,
    activeComposeServices: BASE_COMPOSE_SERVICES.filter((name) => active.has(name)),
    disabledComposeServices: BASE_COMPOSE_SERVICES.filter((name) => !active.has(name)),
  };
}

function yamlQuote(value: string): string {
  return JSON.stringify(value);
}

/**
 * Render the Factory layer that is appended after the pinned official Supabase
 * docker-compose.yml. It removes globally fixed container names, closes database
 * host ports and exposes only a unique loopback API gateway port.
 *
 * Disabled optional services are placed behind a profile which the Factory never
 * activates. Docker Compose >= 2.24.4 is required because !override is used for
 * deterministic port replacement.
 */
export function renderFactoryComposeOverride(
  manifest: ResolvedFactoryManifest,
  allocation: DockerProjectAllocation,
): string {
  const layout = resolveDockerRuntimeLayout(manifest, allocation);
  const disabled = new Set(layout.disabledComposeServices);
  const lines: string[] = [
    "# Generated by Supabase Factory. Do not edit by hand.",
    "# Layer after the pinned official Supabase docker-compose.yml.",
    "services:",
  ];

  for (const service of BASE_COMPOSE_SERVICES) {
    lines.push(`  ${service}:`);
    lines.push("    container_name: !reset null");

    if (disabled.has(service)) {
      lines.push("    profiles: !override");
      lines.push("      - factory-disabled");
    }

    if (service === "api-gw") {
      // Base Envoy depends on Studio only to make the dashboard root route ready.
      // API-only profiles must not start Studio implicitly.
      if (disabled.has("studio")) lines.push("    depends_on: !reset {}");
      lines.push("    ports: !override");
      lines.push(`      - ${yamlQuote(`127.0.0.1:${layout.apiGatewayPort}:8000/tcp`)}`);
    }

    if (service === "supavisor") {
      // DB/session/transaction pooler stay private by default. A future explicit
      // private-network provider may expose them on a trusted interface.
      lines.push("    ports: !reset []");
    }

    if (service === "realtime" && !disabled.has("realtime")) {
      lines.push("    environment:");
      lines.push(`      SELF_HOST_TENANT_NAME: ${yamlQuote(layout.realtimeTenantName)}`);
      lines.push("    networks:");
      lines.push("      default:");
      lines.push("        aliases:");
      lines.push(`          - ${yamlQuote(layout.realtimeDnsName)}`);
    }

    if (service === "storage" && !disabled.has("storage") && manifest.storage.backend === "s3") {
      lines.push("    environment:");
      lines.push("      STORAGE_BACKEND: s3");
      lines.push(`      GLOBAL_S3_BUCKET: ${yamlQuote(manifest.storage.bucketPrefix)}`);
      lines.push(`      REGION: ${yamlQuote(manifest.storage.region)}`);
      lines.push(`      TENANT_ID: ${yamlQuote(manifest.project.id)}`);
      lines.push("      GLOBAL_S3_ENDPOINT: ${FACTORY_S3_ENDPOINT:?FACTORY_S3_ENDPOINT is required}");
      lines.push("      GLOBAL_S3_PROTOCOL: ${FACTORY_S3_PROTOCOL:-https}");
      lines.push("      GLOBAL_S3_FORCE_PATH_STYLE: ${FACTORY_S3_FORCE_PATH_STYLE:-true}");
      lines.push("      AWS_ACCESS_KEY_ID: ${FACTORY_S3_ACCESS_KEY_ID:?FACTORY_S3_ACCESS_KEY_ID is required}");
      lines.push("      AWS_SECRET_ACCESS_KEY: ${FACTORY_S3_SECRET_ACCESS_KEY:?FACTORY_S3_SECRET_ACCESS_KEY is required}");
    }
  }

  return `${lines.join("\n")}\n`;
}

export function renderFactoryRuntimeEnv(
  manifest: ResolvedFactoryManifest,
  allocation: DockerProjectAllocation,
): string {
  const layout = resolveDockerRuntimeLayout(manifest, allocation);
  return [
    "# Generated non-secret Supabase Factory runtime settings.",
    `COMPOSE_PROJECT_NAME=${layout.composeProjectName}`,
    "COMPOSE_FILE=docker-compose.yml:docker-compose.factory.yml",
    `FACTORY_PROJECT_ID=${manifest.project.id}`,
    `FACTORY_HOST_ID=${allocation.hostId}`,
    `FACTORY_REALTIME_TENANT=${layout.realtimeTenantName}`,
    `FACTORY_API_GATEWAY_PORT=${layout.apiGatewayPort}`,
    "",
  ].join("\n");
}

/** Replace the official single-project Realtime DNS/Host convention in the
 * copied project runtime. The pinned upstream checkout itself is never modified.
 * Re-applying the same project-specific patch is intentionally a no-op.
 */
export function patchEnvoyRealtimeConfig(source: string, realtimeDnsName: string): string {
  const marker = "realtime-dev.supabase-realtime";
  if (source.includes(marker)) return source.replaceAll(marker, realtimeDnsName);
  if (source.includes(realtimeDnsName)) return source;
  throw new Error("pinned Envoy config no longer contains the expected Realtime host marker; review upstream before upgrading");
}
