create table if not exists public.factory_ci_marker (
  id bigint generated by default as identity primary key,
  marker text not null unique,
  created_at timestamptz not null default now()
);

alter table public.factory_ci_marker enable row level security;

comment on table public.factory_ci_marker is
  'Disposable Supabase Factory CI migration marker; never used by production applications.';
